function dend_goal_sym = generate_goal_path(params)
    % generate a symbolic representation of the default goal path, which
    % corresponds to the path generated by circular surfaces and pulleys

    N_links = params.N_links;
    omega = params.omega;

    syms s real
    dend_goal_sym = sym(zeros(2,1));
    theta_0_total = 0;

    for link = 1:N_links
        theta_0 = params.link(link).eta*(-omega/2 + s*omega);
        L = params.link(link).L;
        dend_goal_sym = dend_goal_sym + rotate_2D(theta_0_total)*[2*cos(theta_0/2)+L*cos(theta_0); 2*sin(theta_0/2)+L*sin(theta_0)]; % circular surfaces
        theta_0_total = theta_0_total + theta_0;
    end
end